#!/usr/bin/env bash
# Install swayward as a selectable session in your login manager, entirely out
# of $HOME apart from one root-owned desktop file the display manager must read.
#
#   contrib/install-session.sh              # install/refresh
#   contrib/install-session.sh --config sway  # also convert ~/.config/sway/config
#   contrib/install-session.sh --uninstall
#   contrib/install-session.sh --no-build  # install existing target binaries
#
# Nothing is copied into /usr. The binary, launcher and config live under
# ~/.local, so refreshing after a rebuild is one command and removing it leaves
# no trace outside $HOME plus the one desktop file.
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")/.."
REPO=$PWD

PREFIX="$HOME/.local"
BINDIR="$PREFIX/bin"
LAUNCHER="$BINDIR/start-swayward"
BIN="$BINDIR/swayward"
# An immutable host (Fedora Atomic and friends) mounts /usr read-only, so
# `sudo install` there fails outright. /usr/local is a symlink into /var on
# those images and stays writable, and display managers scan it too.
SESSIONDIR=/usr/share/wayland-sessions
if ! findmnt -no OPTIONS /usr 2>/dev/null | grep -qw rw; then
	SESSIONDIR=/usr/local/share/wayland-sessions
fi
DESKTOP="$SESSIONDIR/swayward.desktop"
CONFDIR="$HOME/.config/swayward"
PORTALDIR="$HOME/.config/xdg-desktop-portal"
PORTALCONF="$PORTALDIR/swayward-portals.conf"
CONVERT=""
UNINSTALL=0
BUILD=1
PROFILE=release

while [ $# -gt 0 ]; do
	case "$1" in
	--config) CONVERT=$2; shift 2 ;;
	--debug) PROFILE=debug; shift ;;
	--no-build) BUILD=0; shift ;;
	--uninstall) UNINSTALL=1; shift ;;
	-h | --help) sed -n '2,10p' "$0"; exit 0 ;;
	*) echo "unknown option: $1" >&2; exit 2 ;;
	esac
done

if [ "$UNINSTALL" = 1 ]; then
	rm -f "$BIN" "$BINDIR/swaywardmsg" "$LAUNCHER" "$PORTALCONF"
	echo "removed $BIN, $BINDIR/swaywardmsg, $LAUNCHER and $PORTALCONF"
	if [ -e "$DESKTOP" ]; then
		echo "the desktop entry is root-owned; remove it with:"
		echo "  sudo rm $DESKTOP"
	fi
	echo "your config in $CONFDIR was left alone"
	exit 0
fi

BUILDDIR=${SWAYWARD_BUILD_DIR:-target/$PROFILE}
SRCBIN="$BUILDDIR/swayward"
SRCMSG="$BUILDDIR/swaywardmsg"

# Build by default, so the installed binary matches the checkout. --no-build
# exists for packaging tests and requires explicit existing binaries.
CONTAINER=${SWAYWARD_CONTAINER:-swayward-dev}
# Cargo calls the development profile `dev`, although it writes to target/debug.
CARGO_PROFILE=$PROFILE
if [ "$PROFILE" = debug ]; then
	CARGO_PROFILE=dev
fi
CARGO_ARGS="--profile $CARGO_PROFILE -p swayward --bin swayward -p swayward-ipc --bin swaywardmsg"

if [ "$BUILD" = 1 ] && [ -f /run/.containerenv ]; then
	echo "building..."
	# shellcheck disable=SC2086
	cargo build $CARGO_ARGS
elif [ "$BUILD" = 1 ]; then
	if ! command -v distrobox >/dev/null ||
	   ! distrobox list 2>/dev/null | awk -F ' *\\| *' -v name="$CONTAINER" \
	       'NR > 1 && $2 == name { found = 1 } END { exit !found }'; then
		echo "build container '$CONTAINER' is missing; run contrib/dev-container.sh or use --no-build" >&2
		exit 1
	fi
	echo "building in $CONTAINER..."
	distrobox enter "$CONTAINER" -- bash -lc "cd '$REPO' && cargo build $CARGO_ARGS"
fi

for f in "$SRCBIN" "$SRCMSG"; do
	if [ ! -x "$f" ]; then
		echo "build did not produce $f" >&2
		exit 1
	fi
done

# The binary is built in a Fedora toolbox but runs on the host; verify that
# rather than assuming it, because a missing library at login gives you a
# blank screen and no way to read the error.
if ldd "$SRCBIN" 2>&1 | grep -q 'not found'; then
	echo "these libraries are missing on the host:" >&2
	ldd "$SRCBIN" 2>&1 | grep 'not found' >&2
	echo "install them on the host, not in the container." >&2
	exit 1
fi

mkdir -p "$BINDIR" "$CONFDIR" "$PORTALDIR"
install -m755 "$SRCBIN" "$BIN"
install -m755 "$SRCMSG" "$BINDIR/swaywardmsg"
install -m644 resources/swayward-portals.conf "$PORTALCONF"

# Mirror the hardware quirks and environment.d handling from the host's own
# start-sway, so a VM or an unusual GPU behaves the same way it does for sway.
cat > "$LAUNCHER" <<'LAUNCH'
#!/bin/sh
# Generated by contrib/install-session.sh. Edit the generator, not this file.
export XDG_CURRENT_DESKTOP=swayward
export XDG_SESSION_DESKTOP=swayward
export XDG_SESSION_TYPE=wayland

# A stale WAYLAND_DISPLAY or SWAYSOCK inherited into a real session makes the
# compositor try to nest, or adopt another session's IPC socket.
unset WAYLAND_DISPLAY SWAYSOCK I3SOCK DISPLAY

case $(systemd-detect-virt --vm) in
"none" | "") ;;
"kvm")
	# Matches the host's start-sway: virtio_gpu/virgl glitches under pixman
	# with atomic KMS, and kms_swrast crashes gles2 outright.
	export WLR_RENDERER=pixman
	export WLR_DRM_NO_ATOMIC=1
	;;
*)
	export WLR_NO_HARDWARE_CURSORS=1
	;;
esac

# environment.d(5) customizations, via the generator directly. Importing
# `systemd --user show-environment` instead can leave a WAYLAND_DISPLAY behind
# and break startup.
if [ -x /usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator ]; then
	set -o allexport
	eval "$(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)"
	set +o allexport
fi

mkdir -p "$HOME/.local/share/swayward"
LOG="$HOME/.local/share/swayward/session.log"

# --session imports the environment into systemd and D-Bus. Correct for a real
# session, wrong for a nested one.
exec "$HOME/.local/bin/swayward" --session >>"$LOG" 2>&1
LAUNCH
chmod +x "$LAUNCHER"

if [ -n "$CONVERT" ]; then
	case "$CONVERT" in
	sway) SRC="$HOME/.config/sway/config" ;;
	*) SRC="$CONVERT" ;;
	esac
	if [ ! -f "$SRC" ]; then
		echo "no such config: $SRC" >&2
		exit 1
	fi
	OUT="$CONFDIR/config.kdl"
	[ -f "$OUT" ] && cp "$OUT" "$OUT.bak.$(date +%s)" && echo "backed up existing $OUT"
	python3 contrib/sway-to-kdl "$SRC" > "$OUT.new" 2> "$CONFDIR/translation-warnings.txt" || {
		echo "translation failed; see $CONFDIR/translation-warnings.txt" >&2
		exit 1
	}
	mv "$OUT.new" "$OUT"
	echo "converted $SRC -> $OUT"
	W=$(grep -c ': ' "$CONFDIR/translation-warnings.txt" || true)
	[ "$W" -gt 0 ] && echo "$W directives need manual attention: $CONFDIR/translation-warnings.txt"
fi

if [ ! -f "$CONFDIR/config.kdl" ]; then
	install -m644 resources/default-config.kdl "$CONFDIR/config.kdl"
	echo "installed the default config to $CONFDIR/config.kdl"
fi

# Validate before offering to log in. A config error at login is a blank
# screen with the message in a file you cannot read yet.
if ! "$BIN" validate -c "$CONFDIR/config.kdl" >/dev/null 2>&1; then
	echo
	echo "WARNING: $CONFDIR/config.kdl does not validate:" >&2
	"$BIN" validate -c "$CONFDIR/config.kdl" 2>&1 | tail -20 >&2
	echo
	echo "Fix it before selecting the session, or you get a blank screen." >&2
fi

echo
echo "binary:   $BIN ($("$BIN" --version))"
echo "launcher: $LAUNCHER"
echo "config:   $CONFDIR/config.kdl"
echo "portals:  $PORTALCONF"
echo "log:      ~/.local/share/swayward/session.log"
echo

if [ -e "$DESKTOP" ]; then
	echo "session entry already present: $DESKTOP"
else
	TMP=$(mktemp)
	cat > "$TMP" <<ENTRY
[Desktop Entry]
Name=Swayward (dev)
Comment=An i3/sway-compatible Wayland compositor, from $REPO
Exec=$LAUNCHER
Type=Application
DesktopNames=swayward
ENTRY
	echo "One root-owned file is needed, because the display manager only reads"
	echo "$SESSIONDIR. Run:"
	echo
	echo "  sudo install -Dm644 $TMP $DESKTOP"
	echo
	echo "Then Swayward (dev) appears in the session list. Re-run this script"
	echo "after each rebuild; the desktop file never needs touching again."
fi

cat <<'NOTES'

Before you log in, two things worth knowing:

  Keep a way out. Switch to a TTY with Ctrl+Alt+F3 and log in there if the
  session misbehaves; `pkill -9 swayward` from that TTY returns you to the
  greeter. Your existing sway session entry is untouched, so selecting Sway
  again always works.

  If the screen is blank, read ~/.local/share/swayward/session.log from a TTY.
  That is where the launcher sends stdout and stderr.
NOTES
