[package]
name = "swayward-ipc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

description = "Types and helpers for interfacing with swayward, forked from niri."
keywords = ["wayland"]
categories = ["api-bindings", "os"]
readme = "README.md"

[dependencies]
clap = { workspace = true, optional = true }
schemars = { version = "1.2.2", optional = true }
serde.workspace = true
serde_json.workspace = true
pcre2 = "0.2.11"

[features]
clap = ["dep:clap"]
json-schema = ["dep:schemars"]
